// the \\ denotes a <br>
module.exports = {
	original: {
		white: [
			'50,000 volts straight to the nipples',
			'72 virgins',
			'8 oz. of sweet Mexican black-tar heroin',
			'A bag of magic beans',
			'A balanced breakfast',
			'A bitch slap',
			'A bleached asshole',
			// 'A Bop It™',
			'A brain tumor',
			'A bucket of fish heads',
			'A can of whoop-ass',
			'A cooler full of organs',
			'A death ray',
			'A defective condom',
			'A disappointing birthday party',
			'A falcon with a cap on its head',
			'A fetus',
			'A foul mouth',
			'A gassy antelope',
			'A gentle caress of the inner thigh',
			'A good sniff',
			'A homoerotic volleyball montage',
			'A hot mess',
			'A lifetime of sadness',
			'A live studio audience',
			'A mating display',
			'A micropenis',
			'A micropig wearing a tiny raincoat and booties',
			'A middle-aged man on roller skates',
			'A mime having a stroke',
			'A monkey smoking a cigar',
			'A mopey zoo lion',
			'A murder most foul',
			'A pyramid of severed heads',
			'A really cool hat',
			'A robust mongoloid',
			'A sad handjob',
			'A salty surprise',
			'A sassy black woman',
			'A sausage festival',
			'A sea of troubles',
			'A snapping turtle biting the tip of your penis',
			'A spastic nerd',
			'A stray pube',
			'A subscription to Men\'s Fitness',
			'A Super Soaker™ full of cat pee',
			'A thermonuclear detonation',
			'A time travel paradox',
			'A tiny horse',
			'A tribe of warrior women',
			'A windmill full of corpses',
			'A zesty breakfast burrito',
			// 'Aaron Burr',
			'Active listening',
			'Actually taking candy from a baby',
			// 'Adderall™',
			'Advice from a wise, old black man',
			'African children',
			'Agriculture',
			'AIDS',
			'Alcoholism',
			'All-you-can-eat shrimp for $4.99',
			'Altar boys',
			'Amputees',
			'An asymmetric boob job',
			'An erection that lasts longer than four hours',
			'An icepick lobotomy',
			'An M. Night Shyamalan plot twist',
			'An M16 assault rifle',
			// 'An Oedipus complex',
			'An oversized lollipop',
			'An ugly face',
			'An uppercut',
			'Anal beads',
			'Another goddamn vampire movie',
			'Arnold Schwarzenegger',
			'Asians who aren\'t good at math',
			'Assless chaps',
			'Attitude',
			'Auschwitz',
			'Authentic Mexican cuisine',
			'Autocannibalism',
			'AXE Body Spray',
			'Balls',
			'Barack Obama',
			'BATMAN!!!',
			'Battlefield amputations',
			'Bees?',
			'Being a dick to children',
			'Being a motherfucking sorcerer',
			'Being fabulous',
			'Being fat and stupid',
			'Being marginalized',
			'Being on fire',
			'Being rich',
			'Bill Nye the Science Guy',
			'Bingeing and purging',
			'Bitches',
			'Black people',
			'Bling',
			'Boogers',
			'Breaking out into song and dance',
			'Britney Spears at 55',
			'Brown people',
			// 'Capturing Newt Gingrich and forcing him to dance in a monkey suit',
			'Cards Against Humanity',
			'Catapults',
			'Centaurs',
			'Chainsaws for hands',
			'Cheating in the Special Olympics',
			'Child beauty pageants',
			'Children on leashes',
			'Christopher Walken',
			'Chunks of dead prostitute',
			'Civilian casualties',
			'Classist undertones',
			'Coat hanger abortions',
			'Concealing a boner',
			'Consensual sex',
			'Copping a feel',
			'Count Chocula',
			'Crippling debt',
			'Crucifixion',
			'Crystal meth',
			'Cuddling',
			'Cybernetic enhancements',
			'Daddy issues',
			'Darth Vader',
			'Dead babies',
			'Dead parents',
			'Dental dams',
			'Destroying the evidence',
			'Dick Cheney',
			'Dick fingers',
			'Doin\' it in the butt',
			'Doing the right thing',
			// 'Domino\'s™ Oreo™ Dessert Pizza',
			'Drinking alone',
			'Dropping a chandelier on your enemies and riding the rope up',
			'Dry heaving',
			'Dying of dysentery',
			'Dying',
			'Eating all of the cookies before the AIDS bake-sale',
			'Eating the last known bison',
			'Edible underpants',
			'Elderly Japanese men',
			'Embryonic stem cells',
			'Emotions',
			'Erectile dysfunction',
			'Estrogen',
			'Ethnic cleansing',
			'Eugenics',
			'Exactly what you\'d expect',
			'Expecting a burp and vomiting on the floor',
			'Explosions',
			'Extremely tight pants',
			'Famine',
			// 'Fancy Feast®',
			'Farting and walking away',
			'Fear itself',
			// 'Feeding Rosie O\'Donnell',
			'Fiery poops',
			'Figgy pudding',
			'Finger painting',
			'Fingering',
			'Firing a rifle into the air while balls deep in a squealing hog',
			// 'Five-Dollar Footlongs™',
			'Flesh-eating bacteria',
			'Flightless birds',
			'Flying sex snakes',
			'Foreskin',
			'Former President George W. Bush',
			'Free samples',
			'Friction',
			'Friendly fire',
			'Friends with benefits',
			'Frolicking',
			'Full frontal nudity',
			'Funky fresh rhymes',
			'Gandhi',
			'Geese',
			'Genghis Khan',
			'Genital piercings',
			'German dungeon porn',
			'Getting drunk on mouthwash',
			'Getting married, having a few kids, buying some stuff, retiring to Florida, and dying',
			'Getting naked and watching Nickelodeon',
			'Getting really high',
			'Getting so angry that you pop a boner',
			'Ghosts',
			'Giving 110%',
			'Gloryholes',
			'Goblins',
			'God',
			// 'GoGurt®',
			'Golden showers',
			'Grandma',
			'Grave robbing',
			'Growing a pair',
			'Guys who don\'t call',
			'Half-assed foreplay',
			'Harry Potter erotica',
			'Heartwarming orphans',
			'Helplessly giggling at the mention of Hutus and Tutsis',
			'Her Majesty, Queen Elizabeth II',
			'Heteronormativity',
			'Historically black colleges',
			'Home video of Oprah sobbing into a Lean Cuisine®',
			'Homeless people',
			'Hope',
			'Hormone injections',
			'Horrifying laser hair removal accidents',
			'Horse meat',
			'Hospice care',
			'Hot cheese',
			'Hot people',
			'Hot Pockets®',
			'Hulk Hogan',
			'Hurricane Katrina',
			'Inappropriate yodeling',
			'Incest',
			'Italians',
			'Jerking off into a pool of children\'s tears',
			'Jewish fraternities',
			'John Wilkes Booth',
			'Judge Judy',
			'Justin Bieber',
			'Kamikaze pilots',
			'Kanye West',
			'Keanu Reeves',
			'Kids with ass cancer',
			'Lactation',
			'Lady Gaga',
			// 'Lance Armstrong\'s missing testicle',
			'Land mines',
			'Laying an egg',
			'Leaving an awkward voicemail',
			'Leprosy',
			'Licking things to claim them as your own',
			'Lockjaw',
			'Lumberjack fantasies',
			// 'Lunchables™',
			'Making a pouty face',
			'Man meat',
			'Masturbation',
			'Me time',
			'MechaHitler',
			'Men',
			'Menstrual rage',
			'Michael Jackson',
			'Michelle Obama\'s arms',
			'Morgan Freeman\'s voice',
			'Mouth herpes',
			// 'Mr. Clean, right behind you',
			'Muhammed (Praise Be Unto Him)',
			'Multiple stab wounds',
			'Mutually-assured destruction',
			'My collection of high-tech sex toys',
			'My genitals',
			'My humps',
			'My inner demons',
			'My relationship status',
			'My sex life',
			'My soul',
			'My vagina',
			'Natalie Portman',
			'Natural male enhancement',
			'Natural selection',
			'Nazis',
			'Necrophilia',
			'New Age music',
			'Nickelback',
			'Nicolas Cage',
			'Nipple blades',
			'Not giving a shit about the Third World',
			'Not reciprocating oral sex',
			'Not wearing pants',
			'Obesity',
			'Object permanence',
			'Old-people smell',
			'One trillion dollars',
			'Oompa-Loompas',
			'Opposable thumbs',
			'Overcompensation',
			// 'Pabst Blue Ribbon',
			'Pac-Man uncontrollably guzzling cum',
			'Panda sex',
			'Parting the Red Sea',
			'Passable transvestites',
			'Passing a kidney stone',
			'Passive-aggressive Post-it notes',
			'Passive-agression',
			'Pedophiles',
			'Peeing a little bit',
			'Penis envy',
			'Picking up girls at the abortion clinic',
			'Pictures of boobs',
			'Pixelated bukkake',
			'Police brutality',
			'Pooping back and forth. Forever',
			'Poopy diapers',
			'Poor life choices',
			'Poor people',
			'Poorly-timed Holocaust jokes',
			'Porn stars',
			'Powerful thighs',
			'Prancing',
			'Praying the gay away',
			'Preteens',
			'Pretending to care',
			'Puberty',
			'Public ridicule',
			'Pulling out',
			'Puppies!',
			'Queefing',
			// 'Racially-biased SAT questions',
			'Racism',
			'Raptor attacks',
			'Rehab',
			'Repression',
			'Republicans',
			'Riding off into the sunset',
			'Road head',
			'Robert Downey, Jr',
			'RoboCop',
			'Ronald Reagan',
			'Roofies',
			// 'Rush Limbaugh\'s soft, shitty body',
			'Same-sex ice dancing',
			'Sarah Palin',
			'Saxophone solos',
			'Scalping',
			'Science',
			'Scientology',
			'Scrubbing under the folds',
			'Sean Connery',
			'Sean Penn',
			'Self-loathing',
			// 'Seppuku',
			// 'Serfdom',
			'Sexting',
			'Sexual tension',
			'Sexy pillow fights',
			'Shapeshifters',
			'Shaquille O\'Neal\'s acting career',
			'Sharing needles',
			'Shiny objects',
			'Silence',
			'Skeletor',
			'Smallpox blankets',
			'Smegma',
			'Sniffing glue',
			'Some god-damn peace and quiet',
			'Soup that is too hot',
			'Spectacular abs',
			'Sperm whales',
			'Spontaneous human combustion',
			'Stalin',
			'Stephen Hawking talking dirty',
			'Stormtroopers',
			'Stranger danger',
			'Sunshine and rainbows',
			'Surprise sex!',
			'Sweet, sweet vengeance',
			// 'Switching to Geico®',
			'Swooping',
			'Synergistic management solutions',
			'Take-backsies',
			'Taking off your shirt',
			'Tangled Slinkys',
			'Tasteful sideboob',
			'Teaching a robot to love',
			'Teenage pregnancy',
			'Tentacle porn',
			'Testicular torsion',
			'That thing that electrocutes your abs',
			'The American Dream',
			'The Amish',
			'The art of seduction',
			'The Big Bang',
			'The Blood of Christ',
			'The Boy Scouts of America',
			'The Care Bear Stare',
			'The Chinese gymnastics team',
			'The chronic',
			'The clitoris',
			'The Dance of the Sugar Plum Fairy',
			'The Devil himself',
			'The entire Mormon Tabernacle Choir',
			'The female orgasm',
			'The folly of man',
			'The Force',
			'The gays',
			'The glass ceiling',
			'The Great Depression',
			'The Hamburglar',
			'The hardworking Mexican',
			'The heart of a child',
			'The Holy Bible',
			'The homosexual agenda',
			'The Hustle',
			'The inevitable heat death of the universe',
			'The invisible hand',
			'The Jews',
			'The KKK',
			'The Kool-Aid Man',
			'The light of a billion suns',
			'The Little Engine That Could',
			'The Make-A-Wish® Foundation',
			'The milk man',
			'The miracle of childbirth',
			// 'The penny whistle solo from "My Heart Will Go On."',
			'The placenta',
			'The Pope',
			'The profoundly handicapped',
			'The Rapture',
			'The Rev. Dr. Martin Luther King, Jr',
			'The South',
			'The taint; the grundle; the fleshy fun-bridge',
			// 'The Tempur-Pedic® Swedish Sleep System™',
			'The terrorists',
			'The Three-Fifths compromise',
			'The token minority',
			'The Trail of Tears',
			'The true meaning of Christmas',
			'The Underground Railroad',
			'The violation of our most basic human rights',
			'The Virginia Tech Massacre',
			'The World of Warcraft',
			'The Übermensch',
			'Third base',
			'Throwing a virgin into a volcano',
			// 'Tickling Sean Hannity, even after he tells you to stop',
			'Tom Cruise',
			// 'Toni Morrison\'s vagina',
			'Two midgets shitting into a bucket',
			'Unfathomable stupidity',
			'Used panties',
			'Vehicular manslaughter',
			'Viagra®',
			'Vigilante justice',
			'Vigorous jazz hands',
			'Vikings',
			'Waiting \'til marriage',
			'Waking up half-naked in a Denny\'s parking lot',
			'Wearing underwear inside-out to avoid doing laundry',
			'Wet dreams',
			'When you fart and a little bit comes out',
			'Whipping it out',
			'White people',
			'White privilege',
			'Wifely duties',
			'William Shatner',
			'Winking at old people',
			'Wiping her butt',
			'Women in yogurt commercials',
			'Women\'s suffrage',
			'World peace',
			'Yeast',
			'YOU MUST CONSTRUCT ADDITIONAL PYLONS'
		],

		black: [
			{text: "How did I lose my virginity? %s", pick: 1},
			{text: "Why can't I sleep at night? %s", pick: 1},
			{text: "What's that smell? %s", pick: 1},
			{text: "I got 99 problems but %s ain't one.", pick: 1},
			{text: "Maybe she's born with it. Maybe it's %s.", pick: 1},
			{text: "What's the next Happy Meal toy? %s", pick: 1},
			{text: "Here is the church,\\Here is the steeple,\\Open the doors and there is %s.", pick: 1},
			{text: "It's a pity that kids these days are all involved with %s.", pick: 1},
			{text: "During his childhood, Salvador Dali produced hundreds of paintings of %s.", pick: 1},
			{text: "Alternative medicine is now embracing the curative powers of %s.", pick: 1},
			{text: "And the Academy Award for %s goes to %s2.", pick: 2},
			{text: "What's that sound? %s", pick: 1},
			{text: "What ended my last relationship? %s", pick: 1},
			{text: "MTV's new reality show features eight washed-up celebrities living with %s.", pick: 1},
			{text: "I drink to forget %s.", pick: 1},
			{text: "I'm sorry professor, but I couldn't complete my homework because of %s.", pick: 1},
			{text: "What is Batman's guilty pleasure? %s", pick: 1},
			{text: "This is the way the world ends\\This is the way the world ends\\Not with a bang but with %s.", pick: 1},
			{text: "What's a girls best friend? %s", pick: 1},
			{text: "TSA guidelines now prohibit %s on airplanes.", pick: 1},

			{text: "%s. That's how I want to die.", pick: 1},
			{text: "For my next trick, I will pull %s out of %s2.", pick: 2},
			{text: "In the new Disney Channel Original Movie, Hannah Montana struggles with %s for the first time.", pick: 1},
			{text: "%s is a slippery slope that leads to %s2.", pick: 2},
			{text: "What does Dick Cheney prefer?  %s", pick: 1},
			{text: "Dear Abby, I'm having some trouble with %s and would like your advice.", pick: 1},
			{text: "Instead of coal, santa now gives the bad children %s.", pick: 1},
			{text: "What's the most emo? %s", pick: 1},
			{text: "In 1,000 years, when paper money is a distant memory, how will we pay for goods and services? %s", pick: 1},
			{text: "What's the next superhero/sidekick duo? %s and %s2", pick: 2},
			{text: "In M. Night Shyamalan's new movie, Bruce Willis discoveries that %s had really been %s2 all along.", pick: 2},
			{text: "A romantic, candlelit dinner would be incomplete without %s.", pick: 1},
			{text: "%s. Betcha can't just have one!", pick: 1},
			{text: "White people like %s.", pick: 1},
			{text: "%s. High five, bro.", pick: 1},
			{text: "Next from J.K. Rowling: Harry Potter and the Chamber of %s.", pick: 1},
			{text: "BILLY MAYS HERE FOR %s.", pick: 1},
			{text: "In a world ravaged by %s our only solace is %s2.", pick: 2},
			{text: "War! What is it good for? %s", pick: 1},
			{text: "During sex, I like to think about %s.", pick: 1},

			{text: "What are my parents hiding from me? %s", pick: 1},
			{text: "What will always get you laid? %s", pick: 1},
			{text: "in L.A. County Jail, word is you can trade 200 cigarettes for %s.", pick: 1},
			{text: "What did I bring back from Mexico? %s", pick: 1},
			{text: "What don't you want to find in your Kung Pao chicken? %s", pick: 1},
			{text: "What will I bring back in time to convince people that I am a powerful wizard? %s", pick: 1},
			{text: "How am I maintaining my relationship status? %s", pick: 1},
			{text: "%s. It's a trap!", pick: 1},
			{text: "Coming to Broadway this season, %s: The Musical.", pick: 1},
			{text: "While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on %s.", pick: 1},
			{text: "After the earthquake, Sean Penn brought %s to the people of Haiti.", pick: 1},
			{text: "Next on ESPN2, the World Series of %s.", pick: 1},
			{text: "Step 1: %s.\\Step 2: %s2.\\Step 3: Profit", pick: 2},
			{text: "Rumor has it that Vladimir Putin's favorite delicacy is %s stuffed with %s2.", pick: 2},
			{text: "Before I kill you, Mr Bond, I must show you %s.", pick: 1},
			{text: "What gives me uncontrollable gas? %s", pick: 1},
			{text: "What do old people smell like? %s", pick: 1},
			{text: "The class field trip was completely ruined by %s.", pick: 1},
			{text: "When Pharoh remained unmoved, Moses called down a plague of %s.", pick: 1},
			{text: "What's my secret power? %s", pick: 1},
			
			{text: "What's there a ton of in heaven? %s", pick: 1},
			{text: "What would grandma find disturbing, yet oddly charming? %s", pick: 1},
			{text: "I never truly understood %s until I encountered %s2.", pick: 2},
			{text: "What did the U.S. airdrop to the children of Afghanistan? %s", pick: 1},
			{text: "What helps Obama unwind? %s", pick: 1},
			{text: "What did Vin Diesel eat for diner? %s", pick: 1},
			{text: "%s: good to the last drop.", pick: 1},
			{text: "Why am I sticky? %s", pick: 1},
			{text: "What gets better with age? %s", pick: 1},
			{text: "%s: kid-tested, mother-approved.", pick: 1},
			{text: "Daddy, why is mommy crying? %s", pick: 1},
			// {text: "What's Teach for America using to inspire inner city students to succeed? %s", pick: 1},
			{text: "Studies show that lab rats navigate mazes 50% faster after being exposed to %s.", pick: 1},
			{text: "Life for American Indians was forever changed when the White Man introduced them to %s.", pick: 1},
			{text: "I do not know what weapons World War III will be fought with, but World War IV will be fought with %s.", pick: 1},
			{text: "Why do I hurt all over? %s", pick: 1},
			{text: "What am I giving up for Lent? %s", pick: 1},
			{text: "In Michael Jackson's final moments, he thought about %s.", pick: 1},
			{text: "The Smithsonian Museum of Natural History has just opened an interactive exhibit on %s.", pick: 1},
			{text: "When I am the President of the United States, I will create the Department of %s.", pick: 1},
			{text: "Lifetime presents %s, the story of %s2.", pick: 2},
			{text: "When I am a billionaire, I shall erect a 50-foot statue to commemorate %s.", pick: 1},
			{text: "When I was tripping on acid, %s turned into %s2.", pick: 2},
			{text: "that's right, I killed %s. How, you ask? %s2", pick: 2},
			{text: "What's my anti-drug? %s", pick: 1},
			{text: "%s + %s2 = %s3", pick: 3, draw: 2},
			{text: "What never fails to liven up the party? %s", pick: 1},
			{text: "What's the new fad diet? %s", pick: 1},
			{text: "Major League Baseball has banned %s for giving players an unfair advantage.", pick: 1},
			
		]
	},

	first: {
		white: [
			'A beached whale',
			'A big black dick',
			'A bloody pacifier',
			'A crappy little hand',
			'A low standard of living',
			'A nuanced critique',
			'A passionate Latino lover',
			'A rival dojo',
			'A web of lies',
			'A woman scorned',
			'Apologizing',
			'Appreciative snapping',
			'Beating your wives',
			'Being a busy adult with many important things to do',
			'Being a dinosaur',
			'Bosnian chicken farmers',
			'Carnies',
			'Clams',
			'Coughing into a vagina',
			'Dancing with a broom',
			'Deflowering the princess',
			'Dorito breath',
			'Eating an albino',
			'Enormous Scandinavian women',
			'Fabricating statistics',
			'Finding a skeleton',
			'Gandalf',
			'Genetically engineered super-soldiers',
			'George Clooney\'s musk',
			'Getting abducted by Peter Pan',
			'Getting in her pants, politely',
			'Gladiatorial combat',
			'Good grammar',
			'Hipsters',
			'Historical revisionism',
			'Insatiable bloodlust',
			'Jafar',
			'Jean-Claude Van Damme',
			'Just the tip',
			'Leveling up',
			'Literally eating shit',
			'Mad hacky-sack skills',
			'Making the penises kiss',
			'Media coverage',
			'Medieval Times® Dinner & Tournament',
			'Moral ambiguity',
			'My machete',
			'Neil Patrick Harris',
			'Nubile slave boys',
			'Ominous background music',
			'One thousand Slim Jims',
			'Overpowering your father',
			'Panty raids',
			'Pistol-whipping a hostage',
			'Quiche',
			'Quivering jowls',
			'Revenge fucking',
			'Ripping into a man\'s chest and pulling out his still-beating heart',
			'Ryan Gosling riding in on a white horse',
			'Santa Claus',
			'Scrotum tickling',
			'Sexual humiliation',
			'Sexy Siamese twins',
			'Shaft',
			'Slow motion',
			'Space muffins',
			'Statistically validated stereotypes',
			'Sudden Poop Explosion Disease',
			'Suicidal thoughts',
			'The boners of the elderly',
			'The economy',
			'The Fanta® girls',
			'The four arms of Vishnu',
			'The Gulags',
			'The harsh light of day',
			'The hiccups',
			'The shambling corpse of Larry King',
			'Tripping balls',
			'Words, words, words',
			'Zeus\'s sexual appetites'
		],
		black: [
			{text: "An international tribunal has found %s guilty of %s2.", pick: 2},
			{text: "And I would have gotten away with it, too, if it hadn't been for %s!", pick: 1},
			{text: "Dear Sir or Madam, We regret to inform you that the Office of %s has denied your request for %s2.", pick: 2},
			{text: "He who controls %s controls the world.", pick: 1},
			{text: "I learned the hard way that you can't cheer up a grieving friend with %s.", pick: 1},
			{text: "In a pinch, %s can be a suitable substitute for %s2.", pick: 2},
			{text: "In his new self-produced album, Kanye West raps over the sounds of %s.", pick: 1},
			{text: "In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated %s.", pick: 1},
			{text: "In Rome, there are whisperings that the Vatican has a secret room devoted to %s.", pick: 1},
			{text: "In the distant future, historians will agree that %s marked the beginning of America's decline.", pick: 1},
			{text: "Michael Bay's new three-hour action epic pits %s against %s2.", pick: 2},
			{text: "Science will never explain the origin of %s.", pick: 1},
			{text: "The CIA now interrogates enemy agents by repeatedly subjecting them to %s.", pick: 1},
			{text: "The socialist governments of Scandinavia have declared that access to %s is a basic human right.", pick: 1},
			{text: "This season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only %s and his wits.", pick: 1},
			{text: "What brought the orgy to a grinding halt? %s", pick: 1},
			{text: "What has been making life difficult at the nudist colony? %s", pick: 1},
			{text: "What's the gift that keeps on giving? %s", pick: 1},
			{text: "When all else fails, I can always masturbate to %s.", pick: 1},
			{text: "When I pooped, what came out of my butt? %s", pick: 1},
		]
	},
	second: {
		white: [
			'A 55-gallon drum of lube',
			'A bigger, blacker dick',
			'A Burmese tiger pit',
			'A dollop of sour cream',
			'A magic hippie love cloud',
			'A man in yoga pants with a ponytail and feather earrings',
			'A piñata full of scorpions',
			'A sad fat dragon with no friends',
			'A slightly shittier parallel universe',
			'A soulful rendition of "Ol\' Man River."',
			'A squadron of moles wearing aviator goggles',
			'A sweaty, panting leather daddy',
			'A sweet spaceship',
			'All of this blood',
			'An army of skeletons',
			'An ether-soaked rag',
			'An unhinged ferris wheel rolling toward the sea',
			'Another shot of morphine',
			'Basic human decency',
			'Beefin\' over turf',
			'Being awesome at sex',
			'Boris the Soviet Love Hammer',
			'Bullshit',
			'Catastrophic urethral trauma',
			'Daddy\'s belt',
			'Death by Steven Seagal',
			'Dining with cardboard cutouts of the cast of \"Friends.\"',
			'Double penetration',
			'Existing',
			'Fetal alcohol syndrome',
			'Finding Waldo',
			'Fuck Mountain',
			'Getting hilariously gang-banged by the Blue Man Group',
			'Grandpa\'s ashes',
			'Graphic violence, adult language, and some sexual content',
			'Hillary Clinton\'s death stare',
			'Intimacy problems',
			'Jeff Goldblum',
			'Living in a trashcan',
			'Loki, the trickster god',
			'Making a friend',
			'Me',
			'Mild autism',
			'Mooing',
			'My first kill',
			'Nunchuck moves',
			'Oncoming traffic',
			'One Ring to rule them all',
			'Power',
			'Pretty Pretty Princess Dress-Up Board Game®',
			'Pumping out a baby every nine months',
			'Rising from the grave',
			'Scrotal frostbite',
			'Some really fucked-up shit',
			'Special musical guest, Cher',
			'Spring break!',
			'Subduing a grizzly bear and making her your wife',
			'Survivor\'s guilt',
			'Swiftly achieving orgasm',
			'Taking a man\'s eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes',
			'The corporations',
			'The day the birds attacked',
			'The Google',
			'The grey nutrient broth that sustains Mitt Romney',
			'The human body',
			// 'The mere concept of Applebee\'s®',
			'The mixing of the races',
			'The new Radiohead album',
			'Tiny nipples',
			'Tongue',
			'Upgrading homeless people to mobile hotspots',
			'Weapons-grade plutonium',
			'Wearing an octopus for a hat',
			'Whining like a little bitch',
			'Whipping a disobedient slave'
		],
		black: [
			{text: "%s would be woefully incomplete without %s2.", pick: 2},
			{text: "After months of debate, the Occupy Wall Street General Assembly could only agree on \"More %s!\"", pick: 1},
			{text: "Before %s, all we had was %s2.", pick: 2},
			{text: "Before I run for president, I must destroy all evidence of my involvement with %s.", pick: 1},
			{text: "Charades was ruined for me forever when my mom had to act out %s.", pick: 1},
			{text: "During his midlife crisis, my dad got really into %s.", pick: 1},
			{text: "Everyone down on the ground! We don't want to hurt anyone. We're just here for %s.", pick: 1},
			{text: "I spent my whole life working toward %s, only to have it ruined by %s2.", pick: 2},
			{text: "I went from %s to %s2, all thanks to %s3.", pick: 3, draw: 2},
			{text: "If God didn't want us to enjoy %s, he wouldn't have given us %s2.", pick: 2},
			{text: "In his newest and most difficult stunt, David Blaine must escape from %s.", pick: 1},
			{text: "Little Miss Muffet Sat on a tuffet, Eating her curds and %s.", pick: 1},
			{text: "Members of New York's social elite are paying thousands of dollars just to experience %s.", pick: 1},
			{text: "My country, 'tis of thee, sweet land of %s.", pick: 1},
			{text: "My mom freaked out when she looked at my browser history and found %s.com/%s2.", pick: 2},
			{text: "My new favorite porn star is Joey \"%s\" McGee.", pick: 1},
			{text: "Next time on Dr. Phil: How to talk to your child about %s.", pick: 1},
			{text: "Only two things in life are certain: death and %s.", pick: 1},
			{text: "The Five Stages of Grief: denial, anger, bargaining, %s, acceptance.", pick: 1},
			{text: "The healing process began when I joined a support group for victims of %s.", pick: 1},
			{text: "The votes are in, and the new high school mascot is %s.", pick: 1},
			{text: "This is your captain speaking. Fasten your seatbelts and prepare for %s.", pick: 1},
			{text: "This month's Cosmo: \"Spice up your sex life by bringing %s into the bedroom.\"", pick: 1},
			{text: "Tonight on 20/20: What you don't know about %s could kill you.", pick: 1},
			{text: "You haven't truly lived until you've experienced %s and %s2 at the same time.", pick: 2}
		]
	},
	third: {
		white: [
			'That ass',
			'Nothing',
			'Shutting the fuck up',
			'The primal, ball-slapping sex your parents are having right now',
			'A cat video so cute that your eyes roll back and your spine slides out of your anus',
			'Cock',
			'A cop who is also a dog',
			'Dying alone and in pain',
			'Gay aliens',
			'The way white people is',
			'Reverse cowgirl',
			'The Quesadilla Explosion Salad from Chili’s',
			'Actually getting shot, for real',
			'Not having sex',
			'Vietnam flashbacks',
			'Running naked through a mall, pissing and shitting everywhere',
			'Warm, velvety muppet sex',
			'Self-flagellation',
			'The systematic destruction of an entire people and their way of life',
			'Samuel L. Jackson',
			'A boo-boo',
			'Going around punching people',
			'The entire Internet',
			'Some kind of bird-man',
			'Chugging a lava lamp',
			'Having sex on top of a pizza',
			'Indescribable loneliness',
			'An ass disaster',
			'All my friends dying',
			'Putting an entire peanut buter and jelly sandwich into the VCR',
			'Spending lots of money',
			'Some douche with an acoustic guitar',
			'Flying robots that kill people',
			'A greased-up Matthew McConaughey',
			'An unstoppable wave of fire ants',
			'Not contributing to society in any meaningful way',
			'An all-midget production of Shakespeare’s Richard III',
			'Screaming like a maniac',
			'The moist, demanding chasm of his mouth',
			'Filling every orifice with butterscotch pudding',
			'Unlimited soup, salad, and breadsticks',
			'Crying into the pages of Sylvia Plath',
			'Velcro',
			'A PowerPoint presentation',
			'A surprising amount of hair',
			'Eating Tom Selleck’s mustache to gain his powers',
			'Roland the Farter, flatulist to the king',
			'A pile of squirming bodies',
			'Buying the right pants to be cool',
			'Blood farts',
			'Three months in the hole',
			'A botched circumcision',
			'The Land of Chocolate',
			'Slapping a racist old lady',
			'A lamprey swimming up the toilet and latching onto your taint',
			'Jumping out at people',
			'A black male in his early 20s, last seen wearing a hoodie',
			'Mufasa’s death scene',
			'Bill Clinton, naked on a bearskin rug with a saxophone',
			'Demonic possession',
			'The Harlem Globetrotters',
			'Vomiting mid-blowjob',
			'My manservant, Claude',
			'Having shotguns for legs',
			'Letting everyone down',
			'A spontaneous conga line',
			'A vagina that leads to another dimension',
			'Disco fever',
			'Getting your dick stuck in a Chinese finger trap with another dick',
			'Fisting',
			'The thin veneer of situational causality that underlies porn',
			'Girls that always be textin’',
			'Blowing some dudes in an alley',
			'Drinking ten 5-hour ENERGYs to get fifty continuous hours of energy',
			'Sneezing, farting, and coming at the same time'
		],
		black: [
			{text: "In the seventh circle of Hell, sinners must endure %s for all eternity.", pick: 1},
			{text: "A successful job interview begins with a firm handshake and ends with %s.", pick: 1},
			{text: "Lovin’ you is easy ’cause you’re %s.", pick: 1},
			{text: "My life is ruled by a vicious cycle of %s and %s2.", pick: 2},
			{text: "The blind date was going horribly until we discovered our shared interest in %s.", pick: 1},
			{text: "%s. Awesome in theory, kind of a mess in practice.", pick: 1},
			{text: "I’m not like the rest of you. I’m too rich and busy for %s.", pick: 1},
			{text: "%s: Hours of fun. Easy to use. Perfect for %s2!", pick: 2},
			{text: "What left this stain on my couch? %s", pick: 1},
			{text: "Call the law offices of Goldstein & Goldstein, because no one should have to tolerate %s in the workplace.", pick: 1},
			{text: "When you get right down to it, %s is just %s2.", pick: 2},
			{text: "Turns out that %s-Man was neither the hero we needed nor wanted.", pick: 1},
			{text: "As part of his daily regimen, Anderson Cooper sets aside 15 minutes for %s.", pick: 1},
			{text: "Money can’t buy me love, but it can buy me %s.", pick: 1},
			{text: "With enough time and pressure, %s will turn into %s2.", pick: 2},
			{text: "And what did you bring for show and tell? %s", pick: 1},
			{text: "During high school I never really fit in until I found %s club.", pick: 1},
			{text: "Hey baby, come back to my place and I’ll show you %s.", pick: 1},
			{text: "After months of practice with %s, I think I’m finally ready for %s2.", pick: 2},
			{text: "To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of %s.", pick: 1},
			{text: "Finally! A service that delivers %s right to your door.", pick: 1},
			{text: "My gym teacher got fired for adding %s to the obstacle course.", pick: 1},
			{text: "Having problems with %s? Try %s2!", pick: 2},
			{text: "As part of his contract, Prince won’t perform without %s in his dressing room.", pick: 1},
			{text: "Listen, son. If you want to get involved with %s, I won’t stop you. Just steer clear of %s2.", pick: 2}
		]
	},
	pax: {
		white: [
			'An immediately regrettable $9 hot dog from the Boston Convention Center',
			'Running out of stamina',
			'Casting Magic Missle at a bully',
			'Getting bitch slapped by Dhalsim',
			'Firefly: Season 2',
			'Rotating shapes in mid-air so that they fit into other shapes when they fall',
			'Jiggle physics',
			'Paying the iron price',
			'Loading from a previous save',
			'Sharpening a foam broadsword on a foam whetstone',
			'The rocket launcher',
			'The depression that ensues after catching ‘em all',
			'Violating the First Law of Robotics',
			'Getting inside the Horadric Cube with a hot babe and pressing the transmute button',
			'Punching a tree to gather wood',
			'Spending the year’s insulin budget on Warhammer 40k figurines',
			'Achieving 500 actions per minute',
			'Forgetting to eat, and consequently dying',
			'Wil Wheaton crashing an actual spaceship',
			'The Klobb',
			'Charging up all the way',
			'Vespene gas',
			'Judging elves by the color of their skin and not by the content of their character',
			'Smashing all the pottery in a Pottery Barn in search of rupees'
		],
		black: [
			{text: "I have an idea even better than Kickstarter, and it’s called %sstarter.", pack: 1},
			{text: "You have been waylaid by %s and must defend yourself.", pack: 1},
			{text: "Action Stations! Action Stations! Set condition one throughout the fleet and brace for %s!", pack: 1},
			{text: "In the final round of this year’s Omegathon, Omeganauts must face off in a game of %s.", pack: 1},
			{text: "Press (down)(down)(back)(forward)(B) to unleash %s.", pack: 1},
			{text: "I don’t know exactly how I got the PAX plague, but I suspect it had something to do with %s.", pack: 1}
		]
	},
	nigrahs: {
		white: [
			'A face like a bucket of smashed crabs',
			'A CENTER FOR ANTS',
			'Smells like Bigfoot\'s dick!',
			'Robots?',
			'A computer',
			'All the downloadin!',
			'fallopian tube spaghetti',
			'A Ham Planet',
			'Menstruation mouthwash',
			'Ghost chips',
			'SHUT THE FUCK UP',
			'I love lamp',
			'A coathanger attached to a vacuum cleaner',
			'LOUD NOISES',
			'ksdljhgsldghj',
			'Sticking a midget to a fat person with super glue'
		],
		black: [
			{text: "%s? Ten-outta-ten!", pick: 1},
			{text: "AND YOU THINK THAT OF ME?\\I AM THE ONE WHO IS %s", pick: 1},
			{text: "Yeah! %s bitch!", pick: 1},
			{text: "WHERE IS HE? %s", pick: 1},
			{text: "You’re an insane, degenerate piece of filth, and you deserve %s", pick: 1},
			{text: "Say my name. %s", pick: 1},
			{text: "%s has to be at least… three times bigger than this!", pick: 1},
			{text: "%s. 60% of the time, it works every time.", pick: 1},
			{text: "But can you do %s in 100!!! browser windows????", pick: 1},
			{text: "Hey kid! I'm %s", pick: 1},
			{text: "WHAT IS THIS?? %s? IT NEEDS TO BE.. %s2!", pick: 2},
			{text: "Argh! Right in the %s!", pick: 1},
			{text: "Your mommas so fat, she's %s!", pick: 1},
			{text: "%s... if you know what I mean.", pick: 1},
			{text: "I cant believe youve done %s", pick: 1},
			{text: "Mmm smells like %s", pick: 1},
			{text: "but I %s from there!", pick: 1},
			{text: "Looks like this %s just got turned into a %s2", pick: 2},
			{text: "Brick.. you killed a guy with %s.", pick: 1},
			{text: "The newly developed engine is fueled by %s.", pick: 1}
		]
	}
};